version: "3.8"

services:
  # Servicio principal de Angular.
  # Sirve la aplicación compilada mediante NGINX.
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sweetpop-angular-container
    ports:
      - "8080:80"
    depends_on:
      - json-server-api

  # Servicio de API REST local usando json-server.
  # Expone el endpoint http://localhost:3000/inventory
  json-server-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: sweetpop-json-server-container
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/app/db.json
